apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: 2.0-rc.2
appVersion: 1.10.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
  - name: enterprise-gateway
    version: "2.5.0"
    repository: "https://charts.spot.io"
