apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: 6.0-rc.29
appVersion: 1.32.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
