apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: 6.1-rc.7
appVersion: 1.37.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
