apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: 3.0.0
appVersion: 1.17.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
  - name: enterprise-gateway
    version: "2.6.0"
    repository: "https://konstellation-io.github.io/enterprise_gateway/"
