apiVersion: v2
name: kdl-server
description: KDL server

type: application
version: v0.15-rc.17
appVersion: v0.22.0
dependencies:
  - name: minio
    version: "3.2.0"
    repository: "https://charts.min.io/"
  - name: enterprise-gateway
    version: "2.5.0"
    repository: "https://charts.spot.io"
