name: Cleaner Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "cleaner/**/*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "cleaner/**/*"

concurrency: build_component

jobs:
  lint-dockerfile:
    uses: konstellation-io/github-workflows/.github/workflows/lint-dockerfile.yaml@v1.6.1
    with:
      component_path: cleaner

  build:
    needs: lint-dockerfile
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@v1.6.1
    with:
      component: cleaner
      component_helm_tag: cleaner.image.tag
      component_path: cleaner
      component_image: cleaner
      values_file: helm/kdl-server/values.yaml
    secrets:
      pat: ${{ secrets.PATNAME }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

