name: Vscode Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "vscode/**/*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "vscode/**/*"

concurrency: build_component

jobs:
  lint-dockerfile:
    uses: konstellation-io/github-workflows/.github/workflows/lint-dockerfile.yaml@v1.7.0
    with:
      component_path: vscode

  build:
    needs: lint-dockerfile
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@v1.7.0
    with:
      component: vscode
      component_helm_tag: userToolsOperator.vscode.image.tag
      component_path: vscode
      component_image: vscode
      values_file: helm/kdl-server/values.yaml
    secrets:
      pat: ${{ secrets.PATNAME }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

